### ISSUE TITLE
Reyneris de la Paz Problema 3 Customer Segmentation.

### ISSUE THREAD

**Issue by rey1996** [Reynold97/NataSquad-AI-Hackathon#5]
Autor: Reyneris de la Paz Pita
    Correo: rey.paz1996@gmail.com
    Número de teléfono: +5354518236
    Repositorio: https://github.com/rey1996/customer-segmentation-problem.git

**Comment by Reynold97** [comment]
Saludos Reyneris
Se confundió de repositorio al levantar la Issue. Disculpe por la
confusión, busque el link del repo en la página del concurso.
